# Config file for automatic testing at travis-ci.org

language: python

cache: 
  - apt
  - pip

notifications:
  email: false

python:
  - 3.4
  - 3.3
  # - "2.7_with_system_site_packages"
  - "3.2_with_system_site_packages"
  # - 2.6
  # - "pypy"

# virtualenv:
  # system_site_packages: true

before_install:
  - sudo pip install conda
  - sudo conda init
  # - sudo conda update conda --yes
  - export PATH=$HOME/py/bin:$PATH

install: conda create -n $HOME/py --yes --file requirements.txt "python=$TRAVIS_PYTHON_VERSION"

script: python setup.py test