# Config file for automatic testing at travis-ci.org

language: python

python:
  # - 3.4
  # - 3.3
  - "2.7_with_system_site_packages"
  - "3.2_with_system_site_packages"
  # - 2.6
  # - "pypy"

# virtualenv:
  # system_site_packages: true

before_install:
# don't install both ATLAS and OpenBLAS
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev
  - sudo apt-get install -qq libblas-dev liblapack-dev
  # - sudo apt-get install -qq libopenblas-dev libopenblas-base
  # - sudo apt-get build-dep -qq python3-numpy python-numpy
  - yes | sudo add-apt-repository ppa:chris-lea/python-numpy
  - yes | sudo add-apt-repository ppa:pythonxy/pythonxy-devel 
  - yes | sudo add-apt-repository ppa:pylab/stable
  - sudo apt-get update -q
  - sudo apt-get install -qq python3-numpy python-numpy 
  - sudo apt-get install -qq python3-scipy python-scipy
  - sudo apt-get install -qq python-pandas
  - pip install .

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script: python setup.py test