# Config file for automatic testing at travis-ci.org

language: python

cache: 
  - apt
  - pip

notifications:
  email: false

python:
  - 3.4
  - 3.3
  # - "2.7_with_system_site_packages"
  - "3.2_with_system_site_packages"
  # - 2.6
  # - "pypy"

# virtualenv:
  # system_site_packages: true

before_install:
  - sudo pip install conda
  - conda init
  - conda update conda --yes
  - deps = 'pip numpy scipy pandas'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  - python setup.py install

install: pip install -r requirements.txt

script: python setup.py test