# Config file for automatic testing at travis-ci.org

language: python

cache: 
  - apt
  - pip

notifications:
  email: false

python:
  - 3.4
  - 3.3
  - 3.2
  # - "2.7_with_system_site_packages"
  # - "3.2_with_system_site_packages"
  - 2.7
  - 2.6
  - "pypy"

# virtualenv:
  # system_site_packages: true

install:
  - sudo pip install conda
  - sudo conda init
  # - sudo conda update conda --yes
  - conda create -p $HOME/py --yes pip numpy scipy pandas "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  - pip install -r requirements.txt
  - pip install .

script: python setup.py test