# Config file for automatic testing at travis-ci.org

language: python

cache: 
  - apt
  - pip

notifications:
  email: false

python:
  - 3.4
  - 3.3
  # - 3.2
  # - "2.7_with_system_site_packages"
  - "3.2_with_system_site_packages"
  - 2.7
  - 2.6
  # - "pypy"

# virtualenv:
  # system_site_packages: true

install:
  - if [[ $TRAVIS_PYTHON_VERSION == "3.2_with_system_site_packages" ]]; then
      echo | sudo add-apt-repository ppa:chris-lea/python-numpy;
      echo | sudo add-apt-repository ppa:pythonxy/pythonxy-devel; # pandas
      echo | sudo add-apt-repository ppa:pylab/stable; # scipy
      sudo apt-get update -q;
      sudo apt-get install -qq python3-numpy python3-scipy python3-pandas python3-pandas-lib;
    else
      sudo pip install conda;
      sudo conda init;
      # - sudo conda update conda --yes
      conda create -p $HOME/py --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy pandas;
      export PATH=$HOME/py/bin:$PATH;
    fi
  - pip install -r requirements.txt
  - pip install .

script: python setup.py test